"""Export the API contract (app/schemas.py) to TypeScript: frontend/src/types/api.ts.

Pydantic -> JSON Schema -> TS. Small hand-rolled converter: our schemas only use objects,
literals, arrays, dicts, optionals and $refs, so no Node dependency is needed in the backend.

Run from backend/:  .venv/Scripts/python scripts/export_types.py
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pydantic import BaseModel  # noqa: E402
from pydantic.json_schema import models_json_schema  # noqa: E402

from app import schemas  # noqa: E402

ROOTS = [
    schemas.Analysis, schemas.JobOut, schemas.UploadResponse, schemas.ObligationReviewRequest,
    schemas.ObligationStatusRequest, schemas.EdgeReviewRequest, schemas.EventDateRequest,
    schemas.RemindRequest, schemas.ApiError, schemas.Health, schemas.ConflictReviewRequest,
    schemas.RemindResponse,
]
ALIASES = {  # Literal aliases worth naming on the TS side too
    "EventKey": schemas.EventKey, "Category": schemas.Category, "Modality": schemas.Modality,
    "JobState": schemas.JobState, "ReviewState": schemas.ReviewState, "ObligationStatus": schemas.ObligationStatus,
    "ResolutionStatus": schemas.ResolutionStatus, "Relation": schemas.Relation, "EdgeStatus": schemas.EdgeStatus,
    "RiskBand": schemas.RiskBand, "FieldProvenance": schemas.FieldProvenance, "ErrorCode": schemas.ErrorCode,
    "EvidenceStatus": schemas.EvidenceStatus, "DateProvenance": schemas.DateProvenance,
    "ExtractionState": schemas.ExtractionState, "DeadlineKind": schemas.DeadlineKind,
    "RiskProvenance": schemas.RiskProvenance, "ConflictKind": schemas.ConflictKind,
}


def lit(values) -> str:
    return " | ".join(f'"{v}"' if isinstance(v, str) else str(v).lower() for v in values)


def ts(s: dict) -> str:
    if "$ref" in s:
        return s["$ref"].split("/")[-1]
    if "anyOf" in s:
        parts = [ts(x) for x in s["anyOf"]]
        return " | ".join(dict.fromkeys(parts))
    if "enum" in s:
        return lit(s["enum"])
    if "const" in s:
        return lit([s["const"]])
    t = s.get("type")
    if t == "array":
        inner = ts(s.get("items", {}))
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if t == "object":
        if "additionalProperties" in s and isinstance(s["additionalProperties"], dict):
            return f"Record<string, {ts(s['additionalProperties'])}>"
        return "Record<string, unknown>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean",
            "null": "null"}.get(t, "unknown")


def interface(name: str, s: dict) -> str:
    required = set(s.get("required", []))
    lines = []
    if s.get("description"):
        lines.append("/** " + " ".join(s["description"].split()) + " */")
    lines.append(f"export interface {name} {{")
    for prop, ps in s.get("properties", {}).items():
        opt = "" if prop in required else "?"
        lines.append(f"  {prop}{opt}: {ts(ps)};")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    _, top = models_json_schema([(m, "serialization") for m in ROOTS], ref_template="#/$defs/{model}")
    defs = top["$defs"]
    out = [
        "// GENERATED by backend/scripts/export_types.py from backend/app/schemas.py. Do not edit.",
        "// Dates are ISO strings: date = \"YYYY-MM-DD\", datetime = RFC 3339. UUIDs are strings.",
        "",
    ]
    for alias, typ in ALIASES.items():
        out.append(f"export type {alias} = {lit(typ.__args__)};")
    out.append("")
    body = []
    for name in sorted(defs):
        body.append(interface(name, defs[name]))
        body.append("")
    text = "\n".join(body)
    for alias, typ in sorted(ALIASES.items(), key=lambda kv: -len(lit(kv[1].__args__))):
        text = re.sub(r"(?<=: )" + re.escape(lit(typ.__args__)) + r"(?=( \| null)?;)", alias, text)
    out.append(text)
    out.append(f"export const STAGES = {schemas.STAGES!r} as const;".replace("'", '"'))
    out.append(f"export const DISCLAIMER = {schemas.DISCLAIMER!r};".replace("'", '"') if '"' not in schemas.DISCLAIMER
               else f"export const DISCLAIMER = `{schemas.DISCLAIMER}`;")
    target = Path(__file__).resolve().parents[2] / "frontend/src/types/api.ts"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("wrote", target)


if __name__ == "__main__":
    assert all(issubclass(m, BaseModel) for m in ROOTS)
    main()
