// GENERATED by backend/scripts/export_types.py from backend/app/schemas.py. Do not edit.
// Dates are ISO strings: date = "YYYY-MM-DD", datetime = RFC 3339. UUIDs are strings.

export type EventKey = "effective_date" | "po_issued" | "delivery" | "inspection_complete" | "acceptance" | "certificate_submitted" | "invoice_receipt" | "payment" | "notice_given" | "term_start" | "term_end" | "renewal" | "termination" | "other";
export type Category = "payment" | "renewal" | "termination" | "compliance" | "delivery" | "penalty" | "confidentiality" | "other";
export type Modality = "must" | "must_not" | "may";
export type JobState = "queued" | "running" | "done" | "done_with_warnings" | "failed";
export type ReviewState = "proposed" | "confirmed" | "edited" | "rejected";
export type ObligationStatus = "open" | "done" | "blocked" | "waived";
export type ResolutionStatus = "resolved" | "unresolved_trigger" | "conditional_pending" | "no_deadline" | "ambiguous";
export type Relation = "must_precede" | "condition_for" | "depends_on" | "may_trigger";
export type EdgeStatus = "proposed" | "confirmed" | "rejected" | "auto_rejected";
export type RiskBand = "low" | "medium" | "high" | "critical";
export type FieldProvenance = "extracted" | "computed" | "ai_proposed" | "user";
export type ErrorCode = "NOT_PDF" | "TOO_LARGE" | "TOO_MANY_PAGES" | "ENCRYPTED" | "NO_TEXT_LAYER" | "LLM_QUOTA" | "LLM_UNAVAILABLE" | "PARTIAL_EXTRACTION" | "EMPTY_EXTRACTION" | "INTERNAL";
export type EvidenceStatus = "verified" | "unverified";
export type DateProvenance = "contract_text" | "user_event" | "completion";
export type ExtractionState = "ok" | "extraction_failed" | "no_obligations";
export type DeadlineKind = "absolute" | "relative" | "recurring" | "none";
export type RiskProvenance = "computed" | "extracted" | "user";
export type ConflictKind = "offset_mismatch" | "day_type_mismatch" | "amount_mismatch" | "date_mismatch" | "notice_period" | "llm";

export interface Amount {
  value: number;
  currency: string | null;
}

export interface Analysis {
  contract: ContractOut;
  as_of: string;
  reviewed_only: boolean;
  clauses: ClauseOut[];
  obligations: ObligationOut[];
  edges: EdgeOut[];
  events: EventOut[];
  conflicts: ConflictOut[];
  review_actions: ReviewActionOut[];
  stats: Stats;
  disclaimer: string;
}

export interface ApiError {
  error_code: ErrorCode;
  message: string;
  action: string;
}

export interface ClauseOut {
  id: string;
  section_ref: string | null;
  heading: string | null;
  category: Category | null;
  category_source: "llm" | "keyword" | null;
  char_start: number;
  char_end: number;
  page_start: number;
  page_end: number;
  text: string;
  extraction_state: ExtractionState;
}

export interface ConflictOut {
  id: string;
  kind: ConflictKind;
  source: "rule" | "llm";
  obligation_ids: string[];
  clause_a: string;
  clause_b: string;
  description: string;
  quote_a: string | null;
  quote_b: string | null;
  status: "open" | "dismissed";
}

export interface ContractOut {
  id: string;
  name: string;
  filename: string | null;
  parties: Party[];
  page_count: number;
  is_sample: boolean;
  cached_at: string | null;
  pipeline_version: string;
  created_at: string;
}

export interface DeadlineRule {
  kind: DeadlineKind;
  raw_text: string | null;
  absolute_date: string | null;
  offset: Offset | null;
  direction: "before" | "after" | null;
  anchor_event: EventKey | null;
  recurrence: "weekly" | "monthly" | "quarterly" | "annually" | null;
  is_conditional: boolean;
}

export interface EdgeOut {
  id: string;
  upstream_id: string;
  downstream_id: string;
  relation: Relation;
  source: "rule" | "llm";
  status: EdgeStatus;
  rationale: string | null;
  evidence_quote: string | null;
  evidence_status: EvidenceStatus;
  page: number | null;
  confidence: number | null;
  reject_reason: string | null;
  propagates: boolean;
}

export interface EdgeReviewRequest {
  action: "confirm" | "reject";
  note?: string | null;
}

export interface EventDateRequest {
  date: string | null;
}

export interface EventOut {
  key: string;
  label: string;
  date: string | null;
  date_source: "contract_text" | "user" | "completion" | null;
  source_obligation_id: string | null;
  dependent_obligation_ids: string[];
}

export interface Health {
  ok: boolean;
  db: boolean;
  pipeline_version: string;
  llm_mode: string;
}

export interface JobOut {
  id: string;
  contract_id: string;
  state: JobState;
  stage: string;
  stage_index: number;
  stage_count: number;
  progress_pct: number;
  message: string | null;
  warnings: string[];
  error_code: ErrorCode | null;
  error_message: string | null;
  error_action: string | null;
}

export interface ObligationOut {
  id: string;
  clause_id: string;
  actor: string;
  counterparty: string | null;
  modality: Modality;
  action: string;
  object: string | null;
  category: Category;
  trigger_event: EventKey | null;
  trigger_label: string | null;
  produces_event: EventKey | null;
  is_conditional: boolean;
  condition_text: string | null;
  deadline_rule: DeadlineRule;
  amount: Amount | null;
  penalty_text: string | null;
  cross_refs: string[];
  evidence_quote: string;
  evidence_start: number | null;
  evidence_end: number | null;
  evidence_status: EvidenceStatus;
  evidence_score: number | null;
  page_start: number;
  page_end: number;
  page_approx: boolean;
  llm_confidence: number | null;
  confidence: number;
  due_date: string | null;
  resolution_status: ResolutionStatus;
  resolution_trace: string | null;
  date_provenance: DateProvenance | null;
  next_occurrences: string[];
  review_state: ReviewState;
  needs_review: boolean;
  status: ObligationStatus;
  completed_on: string | null;
  field_provenance: Record<string, "extracted" | "computed" | "ai_proposed" | "user">;
  risk: Risk;
}

/** Editable fields. Anything set here gets field_provenance = "user". */
export interface ObligationPatch {
  actor?: string | null;
  counterparty?: string | null;
  modality?: Modality | null;
  action?: string | null;
  object?: string | null;
  category?: Category | null;
  trigger_event?: EventKey | null;
  produces_event?: EventKey | null;
  deadline_rule?: DeadlineRule | null;
  penalty_text?: string | null;
}

export interface ObligationReviewRequest {
  action: "confirm" | "edit" | "reject";
  patch?: ObligationPatch | null;
  note?: string | null;
}

export interface ObligationStatusRequest {
  status: ObligationStatus;
  occurred_on?: string | null;
}

export interface Offset {
  value: number;
  unit: "day" | "week" | "month" | "year";
  day_type: "calendar" | "business" | "unspecified";
}

export interface Party {
  name: string;
  role: string | null;
}

export interface PathStep {
  edge_id: string;
  upstream_id: string;
  downstream_id: string;
  relation: Relation;
  quote: string | null;
  page: number | null;
}

export interface RemindRequest {
  email: string;
}

export interface ReviewActionOut {
  id: number;
  target_type: "obligation" | "edge" | "event";
  target_id: string;
  action: string;
  before: Record<string, unknown> | null;
  after: Record<string, unknown> | null;
  note: string | null;
  at: string;
}

export interface Risk {
  score: number;
  band: RiskBand;
  factors: RiskFactor[];
  label: string;
}

export interface RiskFactor {
  factor: string;
  points: number;
  provenance: RiskProvenance;
  detail: string | null;
  path: PathStep[] | null;
}

export interface Stats {
  clauses: number;
  obligations: number;
  unresolved_dates: number;
  needs_review: number;
  clauses_without_obligations: number;
  warnings: string[];
}

export interface UploadResponse {
  contract_id: string;
  job_id: string | null;
  cached: boolean;
}

export const STAGES = ["extract_pages", "segment_clauses", "extract_obligations", "verify_dedupe", "dates", "edges", "conflicts", "done"] as const;
export const DISCLAIMER = "Conan is an operations aid, not legal advice. It flags potential inconsistencies but never decides which clause prevails. Risk scores are attention priority, not a probability of breach. Use only fictional or public contracts: free-tier AI inputs may be used by the provider.";
